apiVersion: v1
kind: Namespace
metadata:
  name: cc-ns

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cc-sa
  namespace: cc-ns

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cc-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: cc-sa
  namespace: cc-ns

---

apiVersion: v1
kind: Pod
metadata:
  namespace: cc-ns
  name: cc
spec:
  containers:
  - name: customcontroller
    image: go-controller
    imagePullPolicy: IfNotPresent
  serviceAccountName: cc-sa
